version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongdb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGODB_INITDB_DATABASE: todo
    volumes:
      - ./DB/mongodb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb
  backend-service:
    build:
      context: ./taskwise-crud-service
      dockerfile: taskwise-crud-service.dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENVIRONMENT: development
      MONGODB_URI: mongodb://root:example@mongodb:27017
      MONGODB_DB_NAME: todo
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      PORT: 3000
      BASE_URL: /
      DEBUG_LEVEL: debug
      SERVICE_NAME: TaskWiseCrudService
      JWT_SECRET: secret
      JWT_EXPIRES_IN: "84600s"
    depends_on:
      - mongodb
      - mongo-express
  frontend-service:
    build:
      context: ./taskwise-frontend-service
      dockerfile: taskwise-frontend-service.dockerfile
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend-service

