run:
	docker compose up -d
stop:
	docker compose down
run-db:
	docker compose up -d mongodb mongo-express
run-backend:
	docker compose up -d mongodb mongo-express backend-service
test:
	cd ./taskwise-crud-service && npm run test && cd ../taskwise-frontend-service && npm run test;
	
test-be:
	cd ./taskwise-crud-service && npm run test;
test-fe:
	cd ./taskwise-frontend-service && npm run test;
clean:
	docker system prune --all